public class NestedTryAndCatchBlock3 
{
    public static void main(String[]args)
    {
        try
        {
            try
            {
                System.out.println("going to divide");
                int b=5/0;
            }
            catch(ArithmeticException e)
            {
                System.out.println(e);
            }
            try
            {
                int a[]=new int[5];
                a[5]=4;
            }
            catch(ArrayIndexOutOfBoundsException e)
            {
                System.out.println(e);
            }
            System.out.println("Rest of the code1");
        }
        catch(Exception e)
        {
            System.out.println("Rest of the code2");
        }
    }
}
